# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'instagramClone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for instagramClone

	pod 'Firebase/Auth'
	pod 'Firebase/Storage'
	pod 'Firebase/Firestore'

  target 'instagramCloneTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'instagramCloneUITests' do
    # Pods for testing
  end

end
